sudo: required
services:
  - docker

before_install:
  - docker build -t joshlemer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joshlemer/react-test npm test -- --coverage


after_success:
  - docker build -t joshlemer/multi-client ./client
  - docker build -t joshlemer/multi-server ./server
  - docker build -t joshlemer/multi-nginx ./nginx
  - docker build -t joshlemer/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push joshlemer/multi-client
  - docker push joshlemer/multi-server
  - docker push joshlemer/multi-nginx
  - docker push joshlemer/multi-worker




deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-098979332415
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

